### ISSUE TITLE
[RPI2] replacement for pcsx_rearmed?

### ISSUE THREAD

**Issue by nemo93** [libretro/pcsx1-libretro#2]
Hi,

excuse this very naive question but I just got my eyes on this new core and I was wondering if it would make a difference on RPI2 as I got some issues with pcsx_rearmed. I tried to compile this new pcsx1 core in different ways but only one way worked ... sort of! I just couldn't launch any games at all (no err msg thrown by Retropie). So to keep it short:
1. is there any improvement for RPI2 owners? Does it worth spending time on this one?
2. Related to my 1st question, I'd like to open tickets as I got very specific issues with some games I'd like to draw your attention on (MGS for instance, Parasite Eve 2). Should I do this here or under the pcsx_rearmed core? I just can't for now as it's like the issue section of this core has been suspended...

Thanks a lot for all your hard work. I'm afraid I'm a newbie but I could run any specific command or provide you with any input you may ask. I do have some spare time to do some thorough testing sessions if needed as well!!
Cheers,

TS

**Comment by barbudreadmon** [comment]
I built and played successfully on rpi2 with the following command : 
make platform=armvneon -f Makefile.libretro

I didn't see much difference with pcsx_rearmed core (same issues : no multitap and "iS - Internal Section" got a black screen after a few screen), but it seems there is a fix included for PE2, didn't try it though.

**Comment by nemo93** [comment]
I was going a bit mad as I couldn't build this piece of code with your command line => failure every time. So I decided to give a go to the good ol' way, which is as follows... (using gcc/g++ 4.7)

$ export CFLAGS="-mcpu=cortex-a7 -mfpu=neon-vfpv4"
$ export CXXFLAGS="$CFLAGS"
$ git clone https://github.com/libretro/pcsx1-libretro.git
$ cd pcsx1-libretro
$ make -f Makefile.libretro platform="armv neon hardfloat" -j4

This time it worked! and I could launch games etc. Like you I still see no obvious differences with this new core. I'll do further testing for sure. Yet my 2 most annoying bugs are still there (MGS / PE2 even with included fix turned on). I'm going to open cases for those 2.

Thanks for your support anyway! Much appreciated.
